### ISSUE TITLE
Failing in bitbucket pipelines. Need help

### ISSUE THREAD

**Issue by AhsanAyaz** [sylvaindumont/docker-node-karma-protractor-chrome#11]
Throws error 
```
/var/lib/apt/lists/partial is missing
```
<img width="601" alt="screen shot 2018-02-21 at 7 13 00 pm" src="https://user-images.githubusercontent.com/9844254/36484487-4692a0fe-173b-11e8-8a39-cfb1c53f2af7.png">

Here's my pipeline `.yml`

```yml
image: weboaks/node-karma-protractor-chrome:headless
pipelines:
  default:
    - step:
          script:
            - apt-get update
            - apt-get install -y xvfb
            - yarn
            - npm run lint
            - npm run test:xvfb
            - npm run pree2e
            - npm run e2e:xvfb
            - ./node_modules/.bin/ng build -prod
```
